// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPlfPW7hE95BVpoL3Yi5j5dgF9F8Ru5w',
    appId: '1:231155578796:web:faab75ba165147a2d06c09',
    messagingSenderId: '231155578796',
    projectId: 'transapp-c2093',
    authDomain: 'transapp-c2093.firebaseapp.com',
    databaseURL: 'https://transapp-c2093-default-rtdb.firebaseio.com',
    storageBucket: 'transapp-c2093.appspot.com',
    measurementId: 'G-D2FM882W81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ccYTuPZ7Ige5I2ObfcDBRnlkMr7qTtI',
    appId: '1:231155578796:android:257d349d58118618d06c09',
    messagingSenderId: '231155578796',
    projectId: 'transapp-c2093',
    databaseURL: 'https://transapp-c2093-default-rtdb.firebaseio.com',
    storageBucket: 'transapp-c2093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkItqgo-J2KoSKe4y2DMHVezOvBRcRNio',
    appId: '1:231155578796:ios:6f6e3f493a1e0193d06c09',
    messagingSenderId: '231155578796',
    projectId: 'transapp-c2093',
    databaseURL: 'https://transapp-c2093-default-rtdb.firebaseio.com',
    storageBucket: 'transapp-c2093.appspot.com',
    iosBundleId: 'com.example.apprubinho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkItqgo-J2KoSKe4y2DMHVezOvBRcRNio',
    appId: '1:231155578796:ios:e1e0c064e665a1c6d06c09',
    messagingSenderId: '231155578796',
    projectId: 'transapp-c2093',
    databaseURL: 'https://transapp-c2093-default-rtdb.firebaseio.com',
    storageBucket: 'transapp-c2093.appspot.com',
    iosBundleId: 'com.example.apprubinho.RunnerTests',
  );
}
